server {
    listen 80 default_server;
    server_name _;
    index index.html index.htm index.php;
    root /data/wwwroot/default;

    include snippets/php.conf;
    include snippets/security.conf;
    include snippets/static-cache.conf;

    location /nginx_status {
        stub_status on;
        access_log off;
    }

    access_log /data/wwwlogs/access.log;
}
