if ($http_user_agent ~* "python|curl|java|wget|httpclient|okhttp") {
    return 503;
}

location ~ /(src|vendor)/.*\.php$ {
    deny all;
}

location ~ /.well-known {
    allow all;
}

location ~ /\. {
    deny all;
}

location ~ /data {
    deny all;
}
